server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 30
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.czj.rbac.model
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  auto-tag-classes: true
  packages-to-scan: com.czj.rbac.controller
  paths-to-match: /**
  default-produces-media-type: application/json

rbac:
  upload:
    avatar:
      path: /upload/avatar/
      allowed-types: image/jpeg,image/png,image/gif
      max-size: 5242880
  role-levels:
    levels:
      ROLE_SUPER_ADMIN: 100
      ROLE_ADMIN: 80
      ROLE_MANAGER: 60
      ROLE_USER: 10
  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
    expire-time: 43200000
    refresh-expire-time: 86400000
    token:
      blacklist-size: 10000
    ip-check:
      enabled: true
      action: WARN
  cache:
    user-permission:
      expire: 3600
    manager-permission:
      expire: 3600
    user:
      expire: 1800
    role:
      expire: 3600
    permission:
      expire: 3600
    token:
      expire: 7200
  user:
    default-password: "123456"
    password:
      min-length: 6
      max-length: 20
      require-number: true
      require-letter: true
      require-special: false
  log:
    async-enabled: true
    async:
      core-pool-size: 2
      max-pool-size: 5
      queue-capacity: 100
    retention-days: 30
  login-log:
    retention-days: 30
    async:
      enabled: true
  permission:
    admin: "sys:admin"
